name: MediaWiki fetch

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install node-fetch@2 @actions/core @actions/github @octokit/rest js-base64
          npm install -D @types/node @types/node-fetch typescript
      
      - name: Build script
        run: npx tsc --project tsconfig.actions.json

      - name: Login wiki
        id: login
        env:
          MW_API: ${{ secrets.MW_API }}
          MW_USERNAME: ${{ secrets.MW_USERNAME }}
          MW_PASSWORD: ${{ secrets.MW_PASSWORD }}
        run: node .github/dist/login.js
      
      - name: Get content (JS)
        id: content_js
        env:
          MW_API: ${{ secrets.MW_API }}
          MW_COOKIE: ${{ steps.login.outputs.cookie }}
          MW_TARGET_PAGE: "MediaWiki:Gadget-JSprite.js"
        run: node .github/dist/get.js
      
      - name: Compare and create PR (JS)
        if: ${{ steps.content_js.outputs.user }} != "Repository Bot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MW_PAGE_CONTENT: ${{ steps.content_js.outputs.content }}
          GITHUB_TARGET_DIR: "src/JSprite.js"
        run: node .github/dist/pr.js
      
      - name: Upload content (JS)
        env:
          MW_API: ${{ secrets.MW_API }}
          MW_CSRF_TOKEN: ${{ steps.login.outputs.token }}
          MW_COOKIE: ${{ steps.login.outputs.cookie }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MW_TARGET_PAGE: "MediaWiki:Gadget-JSprite.js"
          GITHUB_TARGET_DIR: "src/JSprite.js"
        run: node .github/dist/post.js
      
      - name: Get content (Lua)
        id: content_lua
        env:
          MW_API: ${{ secrets.MW_API }}
          MW_COOKIE: ${{ steps.login.outputs.cookie }}
          MW_TARGET_PAGE: "Module:JSprite"
        run: node .github/dist/get.js
      
      - name: Compare and create PR (Lua)
        if: ${{ steps.content_lua.outputs.user }} != "Repository Bot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MW_PAGE_CONTENT: ${{ steps.content_lua.outputs.content }}
          GITHUB_TARGET_DIR: "src/JSprite.lua"
        run: node .github/dist/pr.js

      - name: Upload content (Lua)
        env:
          MW_API: ${{ secrets.MW_API }}
          MW_CSRF_TOKEN: ${{ steps.login.outputs.token }}
          MW_COOKIE: ${{ steps.login.outputs.cookie }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MW_TARGET_PAGE: "Module:JSprite"
          GITHUB_TARGET_DIR: "src/JSprite.lua"
        run: node .github/dist/post.js
